site_name: whatlies
extra_css: [style.css]
repo_url: https://github.com/RasaHQ/whatlies
site_url: https://rasahq.github.io/whatlies/
site_description: A python package to discover "what lies" in word embeddings.
site_author: Vincent D. Warmerdam @ Rasa Research

nav:
  - Home: index.md
  - Getting Started:
    - What Are Embeddings: tutorial/embeddings/index.md
    - Interactive Visualisation: tutorial/embeddingsets/index.md
    - Language Options: tutorial/languages/index.md
    - Transformation Viz: tutorial/transformations/index.md
    - Scikit-Learn Compatibility: tutorial/scikit-learn.md
    - Observations: tutorial/observations/index.md
    - FAQ: faq.md
  - API:
    - Embedding: api/embedding.md
    - EmbeddingSet: api/embeddingset.md
    - Transformers:
      - Pca: api/transformers/pca.md
      - Umap: api/transformers/umap.md
      - Tsne: api/transformers/tsne.md
      - OpenTsne: api/transformers/opentsne.md
      - Noise: api/transformers/noise.md
      - Add Random: api/transformers/addrandom.md
      - Ivis: api/transformers/ivis.md
    - Language:
      - spaCy: api/language/spacy_lang.md
      - Sense2Vec: api/language/s2v_lang.md
      - fasttext: api/language/fasttext_lang.md
      - CountVector: api/language/countvector_lang.md
      - BytePair: api/language/bpemb_lang.md
      - ConveRT: api/language/convert_lang.md
      - Gensim: api/language/gensim_lang.md
      - Huggingface: api/language/transformers.md
      - TFHub: api/language/tfhub.md
  - Roadmap: roadmap.md
  - Releases: releases.md
plugins:
  - mkdocstrings
  - search
copyright: Copyright &copy; 2020 <a href="https://twitter.com/Rasa_HQ">Rasa</a>, Maintained by <a href="https://twitter.com/fishnets88">Vincent</a>.
theme:
  name: material
  custom_dir: theme/
  favicon: images/fig.png
  logo:
    icon: album
  feature:
    tabs: true
  palette:
    primary: white
    accent: purple
markdown_extensions:
  - toc:
      permalink: true
